---
title: "Curriculum Vitae"
---

## Professional experience
**Researcher** [2024 - today]{style="float:right"}<br>
 English and Digital Linguistics, TU Chemnitz<br>

**Scientific assistant** [2019 - 2022]{style="float:right"}<br>
 English Language and Linguistics, TU Chemnitz<br>
 - Coordinator of two DAAD projects with Southeast Europe<br>
 - Statistical analysis, corpus preparation, annotation of sociolinguistic interviews, research and editing
<br>

**Internship Linguistics** [03 - 05.2020]{style="float:right"}<br>
 VICO Research and Consulting near Stuttgart<br>
 - Modeling of search queries for social media monitoring on customer topics<br>
 - Annotation of posts from the social web according to tonality
<br>

**Scientific assistant** [2017 - 2019]{style="float:right"}<br>
 English Literatures, TU Chemnitz
<br>

## Education

PhD, English Language and Linguistics, Chemnitz University of Technology [2020 - 01.2024]{style="float:right"}<br> 
"Perception and production of word stress cues in Slavic English varieties" (summa cum laude)

MA English and American Studies at TU Chemnitz [2017 - 2020]{style="float:right"}<br>

BA English and American Studies at TU Chemnitz [2014 - 2017]{style="float:right"}<br>

Semester abroad at Université de Poitiers, France [2016 - 2017]{style="float:right"}<br>

## Awards

Saxon State Scholarship for PhD studies [2020 - 2023]{style="float:right"}<br>
DAAD prize for excellent achievements of international students [2020]{style="float:right"}<br>
Marie-Pleißner prize for excellent Master’s thesis [2020]{style="float:right"}<br>
H. Charles-Lipmann prize for poetry in English [2018]{style="float:right"}<br>

## Teaching

See <a href="https://mbisivan.github.io/pages/teaching.html" target="_blank">Teaching</a>

## Publications

See <a href="https://mbisivan.github.io/pages/publications.html" target="_blank">Publications</a>

## Talks and Workshops

See <a href="https://mbisivan.github.io/pages/presentations.html" target="_blank">Talks</a>

## Skills
Bulgarian (native), English (fluent), German (fluent)<br>
Statistical analysis - R, Matlab<br>
Phonetic analysis and resynthesis - Praat<br>
Transcription and annotation of audio data - Praat, ELAN, GAT<br>
Text analysis and annotation - AntConc, INCEpTION, Python<br>
Version control -- Git 


## Organisation
Organised workshops and summer schools in the frame of the DAAD projects "From Uncertainty to Confidence and Trust" (2020),  "Constructing Confidence and Trust Online" (2021) and "Comparing Confidence and Trust Online and Offline" (2022).

## Memberships

**International Society for the Linguistics of English (ISLE)** [2024 - present]{style="float:right"}<br>
**Deutsche Gesellschaft für Sprachwissenschaft (DGfS)** [2024 - present]{style="float:right"}<br>
**Associated member at the Collaborative Research Center "Hybrid Societies"**, TU Chemnitz [2022 - 2023]{style="float:right"}<br>

## Research stays
Data acquisition at the Masaryk University Brno, Czech Republic [30.10-04.11.22, 8-12.11.21]{style="float:right"}<br>


## Additional activities
Bulgarian transcriber for <a href="https://www.smg.surrey.ac.uk/projects/declining-case-inflectional-loss-in-progress/" target="_blank">"Declining Case: Inflectional Loss in Progress"</a>,
University of Surrey [2024 - today]{style="float:right"}<br>
Alumna ambassador for the TU Chemnitz for Bulgaria [2023 - 2025]{style="float:right"}<br>
Summer School "Digital Humanities" at UNIMORE Modena, Italy [2021, 2022]{style="float:right"}<br>
Assistant of international students at the TU Chemnitz Student Buddy program [2015 - 2023]{style="float:right"}<br>
Student ambassador of the English Department publishing blog posts on Campus TUschler [2015 - 2020]{style="float:right"}<br>

\vfill





