---
title: Publications
--- 
## Journal articles

- Ivanova, M., Neubert, C. R., Schmied, J., & Bendixen, A. (2023). ERP evidence for Slavic and German word stress cue sensitivity in English. Frontiers in Psychology 14. doi: <a href="https://doi.org/10.3389/fpsyg.2023.1193822" target="_blank">10.3389/fpsyg.2023.1193822</a> (Preprint PsyArXiv doi: <a href="http://doi.org/10.31234/osf.io/hqr34" target="_blank">10.31234/osf.io/hqr34</a>)

- Ivanova, M. & Schmied, J. (2023). From cues to features: Bridging psycho- and sociolinguistics in the development of non-native English stimuli. TESOL Communications 2(2), 1-17. doi: <a href="https://doi.org/10.58304/tc.20230201" target="_blank">10.58304/tc.20230201</a>

- Ivanova, M. (2023). German English-medium linguistics journal abstracts over the last 30 years: Quantitative and qualitative structural developments. TOKEN: A Journal of English Linguistics. 16, 89-113. <a href="https://token.ujk.edu.pl/wp-content/uploads/04_M_Ivanova.pdf" target="_blank">https://token.ujk.edu.pl/wp-content/uploads/04_M_Ivanova.pdf</a>

- Schmied, J., & Ivanova, M. (2023). English MA Theses at a German University before and after the Bologna reform: Comparing global rhetorical structures and stance in Linguistics and Cultural Studies. TOKEN: A Journal of English Linguistics. 16, 169-196. <a href="https://token.ujk.edu.pl/wp-content/uploads/07_J_Schmied_M_Ivanova.pdf" target="_blank">https://token.ujk.edu.pl/wp-content/uploads/07_J_Schmied_M_Ivanova.pdf</a>

- Ivanova, M. (accepted). Training word stress perception and production with technology. _The EUROCALL Review_.
  
## Edited volumes

- Schmied, J., & Ivanova, M. (Eds.) (2023). <a href="https://cuvillier.de/de/shop/publications/8837-comparing-confidence-and-trust-online-and-offline" target="_blank">*Comparing confidence and trust online and offline*</a>. REAL19. Cuvillier.

- Schmied, J., Dheskali, J., & Ivanova, M. (Eds.) (2022). <a href="https://cuvillier.de/de/shop/publications/8661-from-uncertainty-to-confidence-and-trust" target="_blank">*From uncertainty to confidence and trust*</a>. Cuvillier.

## Contributions to edited volumes

- Ivanova, M. (2022). Uncertainty in postgraduate training and supervision: A needs analysis for online course development. In J. Schmied, J. Dheskali, & M. Ivanova (Eds.), *From uncertainty to confidence and trust* (pp. 131-146). Cuvillier.

- Ivanova, M. (2020). Semantic and pragmatic truth implications of concession in single- and double-blind open peer reviews. In J. Schmied & J. Dheskali (Eds.), *Conflicting truths in academic and journalistic writing* (pp. 141-156). Cuvillier.

- Petrovska, I., & Ivanova, M. (2020). Teaching lexical patterns in English and Macedonian media discourse: Confronting issues of conflicting truths. In J. Schmied & J. Dheskali (Eds.), *Conflicting truths in academic and journalistic writing* (pp. 269-282). Cuvillier.

## Book reviews

- Ivanova, M. (2022). [Review of the book *Scientific and Parascientific Communication* edited by P. Mur-Dueñas and R. Lorés] *Discourse and Interaction 15*(2), 151-154. <a href="https://journals.muni.cz/discourse-and-interaction/article/view/32959" target="_blank">https://journals.muni.cz/discourse-and-interaction/article/view/32959</a>

- Ivanova, M. (2021). [Review of the book *Academic Writing with Corpora. A Resource Book for Data-Driven Learning*, by T. Karpenko-Seccombe] *Discourse and Interaction*, *14*(2), 126-130. <a href="https://journals.muni.cz/discourse-and-interaction/article/view/18670/14733" target="_blank">https://journals.muni.cz/discourse-and-interaction/article/view/18670/14733</a>

## Media Articles

- Ivanova, M. 20.09.22. Creating Confidence and Trust in Southeast Europe. <a href="https://www.tu-chemnitz.de/tu/pressestelle/aktuell/11476/en" target="_blank">*Uni aktuell*</a>.

- 27.07.22. "War", "Conflict", or "Special Operation"? Confidence and Trust in Digital Discourse. <a href="https://www.tu-chemnitz.de/tu/pressestelle/aktuell/11399/en" target="_blank">*Uni aktuell*</a>.

- 03.11.21. Confidence and Trust in Hybrid Communication. <a href="https://www.tu-chemnitz.de/tu/pressestelle/aktuell/10983/en" target="_blank">*Uni aktuell*</a>.

- 29.01.21. Internationalisation from Home. <a href="https://www.tu-chemnitz.de/tu/pressestelle/aktuell/10550/en" target="_blank">*Uni aktuell*</a>.

- 11.06.19. How to deal with conflicting truths. <a href="https://www.tu-chemnitz.de/tu/pressestelle/aktuell/9509/en" target="_blank">*Uni aktuell*</a>.
